#!/usr/bin/env python

import os
import re
import sys

from file_definitions import REQUIRES_PANDOC, README_ORG, README_MD


def get_changed_files():
    return os.popen('git diff --cached --name-only --diff-filter=ACM') \
        .read().strip().split('\n')


def is_tracked(path):
    return os.system('git ls-files --error-unmatch {}'.format(path)) == 0


def add_to_commit(path):
    if not is_tracked(path):
        print('New file: {}. Adding to git.'.format(path))
    print('Adding {} to previous commit.'.format(path))
    os.system('git add {}'.format(path))


def get_pandoc_major_version():
    pandoc_version_string = os.popen('pandoc -v').readline()
    return int(re.search(r'^pandoc (\d)', pandoc_version_string).group(1))


def verify_pandoc():
    '''
    Returns True if the user has pandoc installed.
    '''
    return os.popen('pandoc -v').readline() != ''


def verify(changed_files):
    '''Verify changed files. Raises an exception if something is not right.'''
    if len(set(changed_files) & set(REQUIRES_PANDOC)) and not verify_pandoc():
        raise Exception(
            '''You cannot commit changes to the following files without pandoc:
            {}

            Commit aborted.'''.format('\n\t'.join(REQUIRES_PANDOC)))


def update_readme(source, target):
    # create markdown version of README. Add to commit.
    print('{} changed. Generating {}'.format(source, target))
    markdown_format = 'gfm' if get_pandoc_major_version() >= 2 \
        else 'markdown_github'

    exit_code = os.system(
        'pandoc -t {} -f org -o README.md README.org'.format(markdown_format))
    if exit_code != 0:  # something went wrong. abort commit.
        raise Exception(
            '''The pandoc conversion from org mode to markdown failed.
            Aborting commit. Use `--no-verify` to override.''')
    add_to_commit(target)


def format(format_cmd, file, *flags):
    '''
    Attempts to format code. Returns True if successful.
    Raises an exception if something goes wrong.
    '''
    return_code = os.system('{} {} {}'.format(format_cmd, file, ' '.join(flags)))
    if return_code > 0:  # we encountered an error
        raise Exception('''
        There was an error in formatting the committed code for {}.
        The process exited with code {}'''.format(file, return_code))
    print("Successfully formatted {}".format(file))
    return True


def elm_format(file):
    return format('elm-format', file, '--yes')


def rustfmt(file):
    '''
    If rustfmt successfully reformatted the code it will exit with 0 exit
    status. Exit status 1 signals some unexpected error, like an unknown option
    or a failure to read a file. Exit status 2 is returned if there are syntax
    errors in the input files. rustfmt can't format syntactically invalid code.
    Finally, exit status 3 is returned if there are some issues which can't be
    resolved automatically. For example, if you have a very long comment line
    rustfmt doesn't split it. Instead it prints a warning and exits with 3.
    '''
    return format('rustfmt', file)



def main(changed_files):
    verify(changed_files)
    if README_ORG in changed_files:
        update_readme(README_ORG, README_MD)


    def get_files(extension):
        return [x for x in changed_files if re.search(r'\w+\.{}$'.format(extension), x)]

    for f in get_files('elm'):
        elm_format(f)

    for f in get_files('rs'):
        rustfmt(f)



if __name__ == "__main__":
    print('Performing pre-commit validation.')
    changed_files = get_changed_files()
    try:
        main(changed_files)
    except Exception as e:
        print(e)
        sys.exit(1)
    else:
        print('Successfully passed pre-commit validation.')
