language: rust
rust:
  - nightly
matrix:
  fast_finish: true
deploy:
  - provider: heroku
    api_key:
      secure: KekCmKi2FdW5v6NOyqREtREtNlJrndXPH3FG/97ofjRyiJnxX6jAOva38WE4laWS9vmK6678sDM6NXKNdn42h0vgOIuUJhStCIVJ2xb0t24JjGQPJzrtuH76X3lruL+/cOvpmc3BcRajqPd4jzmrq8FjzStIjd5jaKpRIK+8D2KD7Cywr7RmEaTAXI+tkxnY6OFyBF6XFhEZce9ToLl42ZXwh67bJTLbfwImG78wAA0KwyF3pAUCKxW5wRb3lIO1S26hBmb1fV7rGhvdg5Zf2Ph8Gjsow1ZLfc22eEK52ILjud0KIA5FTW+28M5OLudzpw+EBsdX/WfzpZGYqijirWSAmVDYnNiTDL63WMZe2D0olyLoDc0mc5nG3P7HSHY87uafF3I9yStKj9FnSvq3WT8+NYW6pVr3I10gzOxVA5SCtobd6p4A4Qxp4oGADa3YjkPWcmlNlFv2Td4i+1WDKdniSucXIFphwKr3Zqaa1tpWKwAOrjp5Hx65NQyZ+PoikHXpSqT3N5t+t8dLSH6Gozlv6YjpPwzwK9wxLM0VSHipeC2D64sIPmLYYXExmI7l+Zn5DitL/jaU9YQFl0Y/EVu+02g4Wv6uLMOzmgLg+gqO5+aO+cDFoALCsmYnnaMCacFPED5dTXS2D3qposPxOeztujLR3N2hLGxnDL8Hrx0=
    app:
      master: audiobed
      dev: audiobed-dev
      integrations: audiobed-sandbox
notifications:
  email: false
  slack:
    secure: qxyUBVLeDBwfRaitmaS9BIbzLSiH9jHcEEfLz9fdEY8OvW9Qf/YMmAtlaFXaGWyfVyi7FZDrhBLJ8NbQGeER9HIv8BIXhBn8myPBfGvc7t2WYk1r6Y1A8BXLVWcykPW5mXLD0AJkWiflVu8K648xoRo7dYJhtNr7nzmoudmM9F4X7tpLHHYCNdGDaqUT0KH6R0EnWrSyuv2JlxMntyc8yFw3RuMdr7ODiRaxuLEZ9tm1O6Bq1mq/SNNPZNke9raXHqUTBalQtTo56g646yQ7dMbWA8eHttG6jpxvia7xkR15jSpKZF/bp0uJnVXOX2CtNe54D4jieKgvpjMrmxO98TQ7rW2fI+ndMPBfiP78OwzlBnWadMXPJ7nlhThS/E+4mgMwQZBxjFJ/XnMCLAIwL4ROPnbnIIDSzjqjysCRnfs3WVCJW4jyU93GsaBG2cWIWNd2tDaUIE7toK5uLNxW2aOgVTHbqzfpp3j6dANFX16eKHqwCNOcl2ynDtIsO8sdPPMs5WR4rSpJbY43SqHysZC68mHIaIADDdY9lV6mV/EreJNd013MPPqLFWOstI6jVLuAnyRgvCKD/lG/0LarbLnggwEcdZIk0UWM3aOXPPWRqzm96sqmtPweWCi+CTL3OdGfLPi2CFMqDt9SZG3I7xLaKzDpYywKCt2Hm3wsFt8=
